name: 자동 테스팅

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: 체크아웃
        uses: actions/checkout@v2

      - name: 빌드 및 테스트
        run: |
          make
          ./main example.com
